name: "Install Valgrind"
description: "Install valgrind-macos and cache it."
runs:
  using: "composite"
  steps:
    - run: |
        git clone --branch feat/bug-135 https://github.com/LouisBrunner/valgrind-macos
      shell: bash

    - run: |
        cd valgrind-macos && ./autogen.sh && ./configure && make && cd ..
      shell: bash

    - run: |
        sw_vers > valgrind_fingerprint
        git -C "valgrind-macos" rev-parse HEAD >> valgrind_fingerprint
        cat valgrind_fingerprint
      shell: bash

    - uses: actions/cache@v4
      id: cache
      with:
        path: valgrind-macos
        key: ${{ github.job }}-valgrind-${{ hashFiles('valgrind_fingerprint') }}

    - run: |
        cd valgrind-macos && sudo make install
      shell: bash
